### ISSUE TITLE
error in compilation

### ISSUE THREAD

**Issue by ManishBansiwal29** [PathPlanning/ORCA-algorithm#5]
Hello...!
I am facing when i am trying to compile this on my local pc i am getting these errors i am attaching a screenshot please help me out how to solve these errors
![Screenshot from 2024-03-14 01-43-39](https://github.com/PathPlanning/ORCA-algorithm/assets/52676528/28e92926-c8ec-453b-b53a-d7a38d52278d)

**Comment by haiot4105** [comment]
Hello!

There was an error in the source code that occurred when building with the `MAPF_LOG_FLAG` flag enabled. It was fixed in the last commit. 

Thank you for your message!
